apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "true"
    description: Foundational components for central management of multiple OpenShift Container Platform and Kubernetes clusters
    repository: https://github.com/open-cluster-management/backplane-operator
    support: Red Hat
  labels:
    control-plane: backplane-operator
  name: multicluster-engine-operator
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 2
  selector:
    matchLabels:
      control-plane: backplane-operator
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: backplane-operator
        ocm-antiaffinity-selector: backplane-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - --leader-elect
        command:
        - /app/backplane-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERAND_IMAGE_ADDON_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/addon-manager-rhel9@sha256:db6b37815ff668e1a16ca7f6aade2dee813677b40808d72398eb0e7a46e8247d'
        - name: OPERAND_IMAGE_AZURE_SERVICE_OPERATOR_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/azure-service-operator-rhel9@sha256:5f920c2bd337f783b5a6ddc4c853ff11618da65182b2bd6fea260caf5456a1ba'
        - name: OPERAND_IMAGE_BACKPLANE_MUST_GATHER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/must-gather-rhel9@sha256:ce0ed4a40f2c71d5f51c9db9a1b9611a76944d1d032e396f5acd77432adff189'
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:3430f986afc84c6c2de72ab7c396cea283891a3072022a4b46ffc7de935f35ee'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-agent-rhel9@sha256:705513de170a7b47a039a0fc1ae11cac5de5c2c3609ace4ce075d85a5bcef6d1'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AWS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-aws-rhel9@sha256:9dab07e45b222219834e4ac1e1f85efc079ac149a2ed6db1c9536ac44217999f'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AZURE_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-azure-rhel9@sha256:0907b0200df1c4afaf7592ea053c9defc9e3007dcc55d84382513c3febe9fa43'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_KUBEVIRT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-api-provider-kubevirt-rhel9@sha256:8357d5f44d27d1db7652906a72a6e23742d324eb8dc36b94b5e8bee3214fdfb4'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_BOOTSTRAP
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-bootstrap-rhel9@sha256:4c5d55995a9ddb062b5655aa5e714d166dbdd497e71ddb8ea4abf93445ade656'
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_OPENSHIFT_ASSISTED_CONTROL_PLANE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/capoa-control-plane-rhel9@sha256:88534cd6f74f358019c6fc612d33c8d9fcedb31b9907191db04935f0a5be6775'
        - name: OPERAND_IMAGE_MCE_CAPI_WEBHOOK_CONFIG_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/mce-capi-webhook-config-rhel9@sha256:17504732fb62bc018221092ecbc17b38fdd66bd5ba974620587b8bb9312e4a73'
        - name: OPERAND_IMAGE_CLUSTERCLAIMS_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterclaims-controller-rhel9@sha256:e2c41ae94f598212e8bd8dd998f5df580fc20568c07f1a0dac72cba7abcc5494'
        - name: OPERAND_IMAGE_CLUSTER_CURATOR_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-curator-controller-rhel9@sha256:2fbc0e341e20ac11ebaa29c901250df2b215aee076f7a54c0507c05cfaa83467'
        - name: OPERAND_IMAGE_CLUSTER_IMAGE_SET_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-image-set-controller-rhel9@sha256:3674816439c95ba1e0b772156ae71de135d7736e8a94ac175fcecb0a154d017d'
        - name: OPERAND_IMAGE_CLUSTERLIFECYCLE_STATE_METRICS
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/clusterlifecycle-state-metrics-rhel9@sha256:20986af13979d46792b99ffe5c25c8a5e0c814d9e9cff99fb05077433a63b29e'
        - name: OPERAND_IMAGE_CLUSTER_PROXY
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/cluster-proxy-rhel9@sha256:ccebed98f249797e976f9b80bacabcd4c248bb6e9f885e2768066af318182ea6'
        - name: OPERAND_IMAGE_CONSOLE_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/console-mce-rhel9@sha256:0078ae50f86e68615fcc6c41e26087738e3d1acb0ea191dc46e96ee532bb7f91'
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/discovery-rhel9@sha256:1a456f0c673d92307639406753b60405b58d4012eee909798609263c9a8ace00'
        - name: OPERAND_IMAGE_OPENSHIFT_HIVE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hive-rhel9@sha256:f86c9d80fe8d0d7aa9879274ce23c220cfde761f356e49165abcb063ec5c590d'
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-addon-rhel9-operator@sha256:906d50f7fe8d6f085274e278ab7000f5fa80e14056d487c33bb8e67fe8159c5c'
        - name: OPERAND_IMAGE_HYPERSHIFT_CLI
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-cli-rhel9@sha256:30b655b47644ee72ef46f21ce12a49f034566a17b52fcc7c3f4cfaa6bf090532'
        - name: OPERAND_IMAGE_HYPERSHIFT_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/hypershift-rhel9-operator@sha256:296910031363bbdc803ebfc3305b6e667b8af3d4fc6e793fd9574fa1c13b02d0'
        - name: OPERAND_IMAGE_IMAGE_BASED_INSTALL_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/image-based-install-rhel9@sha256:93f4130e976adddbceb3ddeebcedfeab8b2e810d242e7be80954dae9a311734c'
        - name: OPERAND_IMAGE_KUBE_RBAC_PROXY_MCE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/kube-rbac-proxy-mce-rhel9@sha256:6669df74228b206441f5369ae65aa8193ea3b00ce5c93daec301bc07569d1429'
        - name: OPERAND_IMAGE_MANAGEDCLUSTER_IMPORT_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managedcluster-import-controller-rhel9@sha256:8cbae2f9a6fc8dd40b8aec03f2ea278bd670e106ce636bd7fd043facbc6f36bc'
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/managed-serviceaccount-rhel9@sha256:029e5605e0503fac44e974f722e378f7d79a5f32ed1827fec0778c451a68f95e'
        - name: OPERAND_IMAGE_MULTICLOUD_MANAGER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/multicloud-manager-rhel9@sha256:9d54bd16bc7c07b45a24fa00337efe055534ddfd659d2459ecc8dd4c9377da6e'
        - name: OPERAND_IMAGE_PROVIDER_CREDENTIAL_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/provider-credential-controller-rhel9@sha256:24b1d7aeb7f4ed91925aff13d5ab1d241913c842f207bcc17444f086c1b25bca'
        - name: OPERAND_IMAGE_PLACEMENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/placement-rhel9@sha256:212a234147cfcd7c6c18d092588d55a1ce554ffe9ddc99aa0463a24bdb9b6c4d'
        - name: OPERAND_IMAGE_REGISTRATION
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-rhel9@sha256:c38deaddaed80cd771afeac7788cb51e751dd1f257cdc59990f634080543154c'
        - name: OPERAND_IMAGE_REGISTRATION_OPERATOR
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/registration-operator-rhel9@sha256:87d17bd0b79e7ed648296aeb97af35dd12eef7e78d8105a028a1591e9174d675'
        - name: OPERAND_IMAGE_WORK
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/work-rhel9@sha256:1226e394e5fede97efeb2aae2f793971ef364e4a1aaa46d867d75d436c53209b'
        - name: OPERAND_IMAGE_ASSISTED_IMAGE_SERVICE
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-image-service-rhel9@sha256:22ee48612a7e4f7badd64b727339bce3a2d590ffae6c353872140fa2fae95e84'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-rhel9@sha256:7b5990495b59646693dc7f6e6408db59cae1d780266b70001ab848275773fd5c'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_AGENT
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-agent-rhel9@sha256:5189821ba937e95b6ebba3ac6aa7b880ade6ac184175f5c3f380c8973742a20a'
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_CONTROLLER
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-installer-controller-rhel9@sha256:1fcbba2bf725e886f67b4d4280915733dfaa58a1826e38d536a751ee3453a235'
        - name: OPERAND_IMAGE_ASSISTED_SERVICE_9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/assisted-service-9-rhel9@sha256:8176f9220a1eccabab8ba561ef0264be16ead2a0888479fd034535fdcf65e976'
        - name: OPERAND_IMAGE_OSE_CLUSTER_API_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-cluster-api-rhel9@sha256:10de81107196991519e6507df291ad3c2352a1792b1b1b36d466eea73f022bae'
        - name: OPERAND_IMAGE_OSE_BAREMETAL_CLUSTER_API_CONTROLLERS_RHEL9
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/ose-baremetal-cluster-api-controllers-rhel9@sha256:9c1293eaf36a9893fc8e3952aff8d43fb450a86cace31979b16d7b77edcaffe4'
        - name: OPERAND_IMAGE_POSTGRESQL_13
          value: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/postgresql-13@sha256:19266ff13a81c85d42e53734e375a5d341221b2c161ca41d009cc6fbe8906ea2'
        - name: OPERATOR_VERSION
          value: 2.11.1
        - name: OPERATOR_PACKAGE
          value: multicluster-engine
        image: '{{ .Values.imageRegistry }}/{{ .Values.imageRootRepository }}/backplane-rhel9-operator@sha256:3430f986afc84c6c2de72ab7c396cea283891a3072022a4b46ffc7de935f35ee'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: backplane-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      nodeSelector:
        aro-hcp.azure.com/role: infra
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: multicluster-engine-operator
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: infra
        operator: Equal
        value: "true"
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-engine-operator-webhook
status: {}
