apiVersion: v2
appVersion: 2.11.1
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:636672d28d36fc3e72dc4e5260a8621bd3062adfe320e34b3ffe4e5446801e23
type: application
version: 2.11.1
