apiVersion: v1
kind: Service
metadata:
  name: mise
  namespace: '{{ .Values.namespace }}'
spec:
  selector:
    app: mise
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: misev2
  namespace: '{{ .Values.namespace }}'
spec:
  selector:
    app: misev2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
